modLoader="javafml"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GNU LGPLv3"

# A URL to refer people to when problems occur with this mod
issueTrackerURL= "https://github.com/dragoni7/Dreamland-1.19/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="dreamland" 
version="${file.jarVersion}"
displayName="Dreamland"
logoFile="dreamland_logo.png"
credits="Artwork Contributions: oniyannasama"
authors="dragoni7" 
description='''
Enhances your Overworld exploration experience with the addition of a few fantasy inspiried biomes!
'''
[[dependencies.dreamland]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.forge]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.terrablender]]
    modId = "terrablender"
    mandatory = true
    versionRange = "[2.0.0.125,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.geckolib]]
    modId = "geckolib3"
    mandatory = true
    versionRange = "[3.1.16,)"
    ordering = "BEFORE"
    side = "BOTH"

